version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "main.py"]
    depends_on:
      - db

  db:
    image: postgres:12.3
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PORT}:${PORT}